import SwiftUI

/// The app's mark: one block, with an S on it.
///
/// Drawn rather than shipped as an image, and drawn out of `BlockSurface` —
/// the same chrome every block on the tower uses. So the mark cannot drift
/// from the thing it is a picture of: change the rim or the band and the logo
/// changes with them.
///
/// The **app icon** is deliberately not this view, and is no longer a flat
/// pink field either. Jaro's S is an angular ribbon whose outline has four
/// inner corners, and cutting it there splits the letter into the five strokes
/// it is actually built from — so the icon is that same S taken apart at its
/// own joints, each piece drawn as one of the app's blocks in its own colour,
/// on white. It is generated by `tools/make_app_icon.py`, which mirrors the
/// chrome constants; change the rim, wash or band and re-run it.
///
/// One block with a letter on it is still right HERE, at 40pt and up on a warm
/// ground, where the block reads as a block and should look like one.
struct StrataMark: View {
    var side: CGFloat = 44
    /// Mindfulness pink. The mark is a block, so it wears a block's colour
    /// rather than a brand colour invented alongside them.
    private var pink: Color { HabitCategory.mindfulness.style.baseColor }

    var body: some View {
        BlockSurface(
            cornerRadius: GridConstants.blockCornerRadius(forCell: side),
            // Rim weight and blur are absolutes tuned to the tower's cell;
            // at 44pt an unscaled 1.4pt rim is nearly twice as heavy in
            // proportion. `BlockSurface` already takes the ratio.
            scale: side / GridConstants.blockReferenceCell
        ) {
            pink
        }
        .frame(width: side, height: side)
        .overlay {
            // 0.88, not the 0.62 an SF Rounded S wanted. Jaro's S is a much
            // narrower letterform, so the same fraction left it floating in
            // the middle of the block with margin on every side. This puts its
            // cap height at ~58% of the block, which is what the icon does.
            Text("S")
                .font(JaroFont.size(side * 0.88))
                .foregroundStyle(.white)
                // The letter's optical centre sits slightly below its bounding
                // box centre, which is why this is not simply centred.
                .offset(y: -side * 0.01)
        }
        .accessibilityLabel("Strata")
    }
}


/// The app's name, set in Jaro.
///
/// One view so the camera's wordmark and the Settings header cannot drift into
/// two different sizes of the same word — which is exactly what happened to the
/// mini tower this file replaced.
struct StrataWordmark: View {
    var size: CGFloat = 28
    var color: Color = .primary

    var body: some View {
        Text("Strata")
            .font(JaroFont.size(size))
            .foregroundStyle(color)
            .accessibilityLabel("Strata")
    }
}
