import SwiftUI

/// The Strata mark: a blocky S, cut from a rounded square.
///
/// Two bars and a slash, in the same geometry the tower is built from — the
/// outer corners take `BlockSurface`'s own 14.7% radius and the interior
/// angles take about half of it.
///
/// **It is drawn, not shipped as an image.** The vector is generated by
/// `tools/make_logo.py`, which also writes `brand/strata-mark*.svg` for
/// anything outside the app. Change the geometry there and re-run with
/// `--swift` to update the constants below; do not edit them by hand.
///
/// The proportions were chosen by rendering the slash at 0.36 / 0.43 / 0.50 /
/// 0.56 / 0.62 and looking: below 0.43 the letter reads as two bars joined by
/// a hairline; past 0.56 the counters close and it turns into a lozenge.
///
/// **The interior angles round too**, at about half the outer radius. They
/// were knife-sharp on the rule that a block has no rounded inside corners —
/// true of a block, and not true of a letter cut from one, where the two
/// acute corners came to points sharp enough to read as a rendering artefact
/// rather than as a drawn edge.
struct StrataMarkShape: Shape {
    func path(in rect: CGRect) -> Path {
        let side = min(rect.width, rect.height)
        let pts = StrataMarkShape.outline.map {
            CGPoint(x: rect.minX + $0.x * side, y: rect.minY + $0.y * side)
        }

        var path = Path()
        var started = false
        for (i, p) in pts.enumerated() {
            let prev = pts[(i - 1 + pts.count) % pts.count]
            let next = pts[(i + 1) % pts.count]
            let radius = Self.radius(at: i, point: p, prev: prev, next: next, side: side)
            guard radius > 0 else {
                if started { path.addLine(to: p) } else { path.move(to: p); started = true }
                continue
            }
            // Trim back along both edges, then round between them. The same
            // quadratic the generator samples, so the Swift shape, the SVGs
            // and the app icon are one drawing.
            func stepped(_ from: CGPoint, toward: CGPoint) -> CGPoint {
                let dx = toward.x - from.x, dy = toward.y - from.y
                let d = max(hypot(dx, dy), 0.0001)
                return CGPoint(x: from.x + dx / d * radius, y: from.y + dy / d * radius)
            }
            let a = stepped(p, toward: prev)
            let b = stepped(p, toward: next)
            if started { path.addLine(to: a) } else { path.move(to: a); started = true }
            path.addQuadCurve(to: b, control: p)
        }
        path.closeSubpath()
        return path
    }

    /// The radius a corner can actually take.
    ///
    /// Trimming back by more than half of either adjacent edge turns the
    /// corner inside out, and the slash meets the bars at a very acute angle —
    /// this clamp is what lets the interior corners round at all.
    private static func radius(at index: Int, point: CGPoint,
                               prev: CGPoint, next: CGPoint, side: CGFloat) -> CGFloat {
        let wanted = cornerRadii[index] * side
        let a = hypot(point.x - prev.x, point.y - prev.y)
        let b = hypot(point.x - next.x, point.y - next.y)
        return min(wanted, a * 0.5, b * 0.5)
    }

    // Generated by tools/make_logo.py --swift. Do not hand-edit.
    /// The mark's outline in a unit square, y DOWN.
    static let outline: [CGPoint] = [
        CGPoint(x: 0.0000, y: 0.0000), CGPoint(x: 1.0000, y: 0.0000), CGPoint(x: 1.0000, y: 0.3000),
        CGPoint(x: 0.5600, y: 0.3000), CGPoint(x: 1.0000, y: 0.7000), CGPoint(x: 1.0000, y: 1.0000),
        CGPoint(x: 0.0000, y: 1.0000), CGPoint(x: 0.0000, y: 0.7000), CGPoint(x: 0.4400, y: 0.7000),
        CGPoint(x: 0.0000, y: 0.3000)
    ]
    /// One wanted radius per vertex, as a fraction of the side.
    /// The outer corners take the block's ratio; the interior
    /// angles take a smaller one, so the counters read as cut
    /// rather than as knife points.
    static let cornerRadii: [CGFloat] = [
        0.1470, 0.1470, 0.0750, 0.0750, 0.0750,
        0.1470, 0.1470, 0.0750, 0.0750, 0.0750
    ]
}

/// The app's mark, at a size.
///
/// A flat pink letter on the page's own ground — no block behind it, no rim,
/// no frosted band. The mark IS the block's geometry; putting it on a second
/// block was the old construction, and two nested rounded squares is one more
/// than the idea needs.
struct StrataMark: View {
    var side: CGFloat = 44

    /// Mindfulness pink — the app's own colour.
    private var pink: Color { HabitCategory.mindfulness.style.baseColor }

    var body: some View {
        StrataMarkShape()
            .fill(pink)
            .frame(width: side, height: side)
            .accessibilityLabel("Strata")
    }
}


/// The app's name.
///
/// One view so the camera's wordmark and the Settings header cannot drift into
/// two different sizes of the same word.
///
/// Still Jaro. A wordmark constructed in the new mark's geometry lives in
/// `brand/strata-wordmark*.svg` and `tools/make_wordmark.py`, and it is not
/// good enough to replace a professionally drawn face yet — set beside Jaro at
/// camera size its `a` reads as a reversed `c` and its counters close up. The
/// mark and the wordmark do not have to be the same drawing; a heavy geometric
/// face beside a heavy geometric letter is already one family.
struct StrataWordmark: View {
    var size: CGFloat = 28
    var color: Color = .primary

    var body: some View {
        Text("Strata")
            .font(JaroFont.size(size))
            .foregroundStyle(color)
            .accessibilityLabel("Strata")
    }
}
