import SwiftUI

/// The Strata mark: a blocky S, cut from a rounded square.
///
/// Two bars and a slash, in the same geometry the tower is built from — the
/// outer corners take `BlockSurface`'s own 14.7% radius and the interior
/// angles take about half of it.
///
/// **Kept, but not the mark.** It held the job for a day. The argument for it
/// was that a light monoline disappears at 44pt in Settings and at 50pt on a
/// home screen where a solid form holds; the owner's answer is that the logo
/// is the drawn `S`, and that is the call. The shape stays because it is
/// generated by `tools/make_logo.py`, costs nothing, and the small-size
/// question is a real one that may come back.
struct StrataMarkShape: Shape {
    func path(in rect: CGRect) -> Path {
        let side = min(rect.width, rect.height)
        let pts = StrataMarkShape.outline.map {
            CGPoint(x: rect.minX + $0.x * side, y: rect.minY + $0.y * side)
        }

        var path = Path()
        var started = false
        for (i, p) in pts.enumerated() {
            let prev = pts[(i - 1 + pts.count) % pts.count]
            let next = pts[(i + 1) % pts.count]
            let radius = Self.radius(at: i, point: p, prev: prev, next: next, side: side)
            guard radius > 0 else {
                if started { path.addLine(to: p) } else { path.move(to: p); started = true }
                continue
            }
            // Trim back along both edges, then round between them. The same
            // quadratic the generator samples, so the Swift shape, the SVGs
            // and the app icon are one drawing.
            func stepped(_ from: CGPoint, toward: CGPoint) -> CGPoint {
                let dx = toward.x - from.x, dy = toward.y - from.y
                let d = max(hypot(dx, dy), 0.0001)
                return CGPoint(x: from.x + dx / d * radius, y: from.y + dy / d * radius)
            }
            let a = stepped(p, toward: prev)
            let b = stepped(p, toward: next)
            if started { path.addLine(to: a) } else { path.move(to: a); started = true }
            path.addQuadCurve(to: b, control: p)
        }
        path.closeSubpath()
        return path
    }

    /// The radius a corner can actually take.
    ///
    /// Trimming back by more than half of either adjacent edge turns the
    /// corner inside out, and the slash meets the bars at a very acute angle —
    /// this clamp is what lets the interior corners round at all.
    private static func radius(at index: Int, point: CGPoint,
                               prev: CGPoint, next: CGPoint, side: CGFloat) -> CGFloat {
        let wanted = cornerRadii[index] * side
        let a = hypot(point.x - prev.x, point.y - prev.y)
        let b = hypot(point.x - next.x, point.y - next.y)
        return min(wanted, a * 0.5, b * 0.5)
    }

    // Generated by tools/make_logo.py --swift. Do not hand-edit.
    /// The mark's outline in a unit square, y DOWN.
    static let outline: [CGPoint] = [
        CGPoint(x: 0.0000, y: 0.0000), CGPoint(x: 1.0000, y: 0.0000), CGPoint(x: 1.0000, y: 0.3000),
        CGPoint(x: 0.5600, y: 0.3000), CGPoint(x: 1.0000, y: 0.7000), CGPoint(x: 1.0000, y: 1.0000),
        CGPoint(x: 0.0000, y: 1.0000), CGPoint(x: 0.0000, y: 0.7000), CGPoint(x: 0.4400, y: 0.7000),
        CGPoint(x: 0.0000, y: 0.3000)
    ]
    /// One wanted radius per vertex, as a fraction of the side.
    /// The outer corners take the block's ratio; the interior
    /// angles take a smaller one, so the counters read as cut
    /// rather than as knife points.
    static let cornerRadii: [CGFloat] = [
        0.1470, 0.1470, 0.0750, 0.0750, 0.0750,
        0.1470, 0.1470, 0.0750, 0.0750, 0.0750
    ]
}

// MARK: - Drawn lettering

/// A word the owner drew, as a vector asset.
///
/// The three of them — `Strata`, the single `S`, and `Memories` — are one
/// typeface and one mechanism, so they are one view. Each is an SVG in the
/// asset catalogue with `preserves-vector-representation` and
/// `template-rendering-intent: template`, which means the app carries the
/// drawing rather than a bitmap of it: it is resolution-independent at any
/// size and `color` tints it exactly the way it tinted a `Text`.
///
/// **`size` is CAP HEIGHT, not point size.** These drawings have no ascender
/// and no descender — the artboard is the cap — so the frame's top IS the top
/// of the ink. That is why a header made of one takes
/// `GridConstants.headerArtworkTopPadding` and not the version that corrects
/// for where a font sets its cap inside its own box.
///
/// **It scales with Dynamic Type**, which is the one thing artwork usually
/// gives up. `@ScaledMetric` grows the cap height from the same text style the
/// system title would have used — and because the frame's top is the cap top,
/// growing it pushes ink DOWN from a fixed line rather than moving the line,
/// so a larger accessibility size does not drag the header off its rule.
private struct DrawnLettering: View {
    let text: String
    let color: Color
    /// Cap height, grown by Dynamic Type from the style a system title uses.
    @ScaledMetric private var cap: CGFloat

    init(text: String, size: CGFloat, color: Color, relativeTo style: Font.TextStyle) {
        self.text = text
        self.color = color
        self._cap = ScaledMetric(wrappedValue: size, relativeTo: style)
    }

    /// **SF's cap height over its em**, which is how a cap height becomes a
    /// point size. Every caller of these marks specifies a CAP, because the
    /// drawings had no ascender and no descender and their artboard was the
    /// cap — so a header's top rule is cut to the cap and nothing may move it.
    /// Setting `Text` at the cap directly would have made every wordmark in the
    /// app about 40% too small.
    private static let capOverEm: CGFloat = 0.714

    /// A logotype is tracked tighter than a sentence. Proportional to the size
    /// rather than a fixed point value, so it holds at 17pt and at 30.
    private static let trackingShare: CGFloat = -0.022

    /// **The third weight, and the measurement that keeps it.**
    ///
    /// `Typography` has two cuts, Regular and Medium, and this is the one place
    /// in the app that sets a third. It is not an oversight and it is not buried
    /// inside onboarding's device frame: `MemoriesTitle` is the Memories
    /// screen's own title, over MapKit's labels, at full size.
    ///
    /// Measured out of `SFNS.ttf`'s own variable axes rather than guessed. SF
    /// Pro's named instances put Medium at `wght` 510 and Semibold at 590, and
    /// at `opsz` 33.55, the point size this view resolves to from the 23.96pt
    /// screen-title cap, a capital's stem is **0.1097 em at Medium against
    /// 0.1256 at Semibold: 3.68pt against 4.21pt, 14.5% more stroke.** The `M`
    /// advance goes 1459 to 1486 units, 1.9% wider.
    ///
    /// **So putting it on the ladder costs 0.53pt of stem on a title that has to
    /// hold against a live map**, which is the exact thing the drawn letterforms
    /// were photographed winning on. `MemoriesTitle`'s own note says the font's
    /// stroke was "about a fifth lighter" than the drawing; 14.5% is that claim
    /// measured, close and in the right direction. The weight is what bought the
    /// drawing's heft back when it came off, so dropping it hands back the
    /// deficit the comparison was about. One title, in one view, named here so
    /// the exception is on the record instead of contradicting `Typography` in
    /// silence.
    var body: some View {
        let points = cap / Self.capOverEm
        Text(text)
            .font(.system(size: points, weight: .semibold, design: .default))
            .tracking(points * Self.trackingShare)
            .lineLimit(1)
            // **A cap-height frame, still.** The callers that place these
            // against a cut grid line — the camera's header, the head maker's —
            // measure to the cap, and a `Text` carries ascender and descender
            // space above and below its ink. Clipping the box to the cap and
            // letting the glyphs overhang keeps every one of those layouts
            // exactly where it was when these were drawings.
            //
            // Leading, so a width limit cannot push the word sideways: at an
            // accessibility size the parent does not grow, and a centred word
            // in a frame that stayed wide walked 30pt in from the margin.
            .fixedSize()
            .frame(height: cap, alignment: .leading)
            .foregroundStyle(color)
            .accessibilityLabel(text)
    }
}

// **`StrataWordmark` is deleted** (2026-09-30). The owner: "keep it off
// everywhere for now, since we are going to change the name anyway."
//
// It had no callers left once the camera, the head maker and Settings dropped
// it, and a view that sets a word nobody draws is dead code with a name
// attached. The mechanism survives below in `DrawnLettering` — a word, a cap
// height, a weight — so whatever the app ends up called is a four-line struct,
// not a rebuild.

/// The Memories screen's title.
///
/// **In no hand at all now**, like everything else: the drawn letterforms came
/// off on 2026-09-30 and this is a `Text` in a plain semibold sans. It is a
/// screen's name rather than the app's, so it survived the cull that took the
/// wordmark — nothing about it is going to be renamed.
///
/// **This one had the better argument for staying and still goes.** The drawing
/// was photographed against the one SETTING of the same word, light, dark and
/// xxLarge, on the drawer and over the map: the font's stroke was about a fifth
/// lighter, its M narrower, and its bearing put the ink 3pt off the margin.
/// Over the map's own labels the drawing held and the font lost.
///
/// That comparison was between two versions of the same squared-off face. The
/// weight it was losing on is bought back here by setting it semibold, which is
/// what a title over a map needs and what the drawing was supplying by being
/// drawn heavy.
struct MemoriesTitle: View {
    /// Cap height, matched to what the screen-title font actually sets — see
    /// `Typography.screenTitleCap`. Not `screenTitleSize`: that is an em, and
    /// using it made this title half again as tall as the tower's.
    var size: CGFloat = Typography.screenTitleCap
    var color: Color = .primary

    var body: some View {
        DrawnLettering(text: "Memories", size: size, color: color,
                       relativeTo: .largeTitle)
    }
}

// MARK: - The mark

/// The app's mark: the owner's `S`, on one of the app's blocks.
///
/// **The mark and the icon are the same drawing and they are NOT on the same
/// ground.** This said they were, and it was false: the app's
/// `AppColors.warmBlack` is `0x403D39`, and `tools/make_app_icon.py` has its own
/// constant of the same name at `0x1C1A18`. Two colours, one word, two files.
/// Measured: 64 against 28 on the red byte (2.3x), and 0.047 against 0.011 in
/// relative luminance (4.5x). The icon has no rim either. So the home screen and
/// Settings show one letter on two different objects, and a sentence in a
/// comment is what kept anybody from looking.
/// `docs/research/visual-cohesion.md` section 4.4 measured the same gap, and its
/// recommendation is to keep the ICON's darker ground, because that is the one
/// that has to hold on a wall of squircles.
/// **Not changed here.** It moves the app icon's colour and the mark in
/// Settings, it cannot be judged from a diff, and this session could not build
/// or screenshot. It needs the owner's eye on one shot of each.
///
/// It was a three-block ziggurat for a while, argued for from research: a
/// single-letter monogram carries no meaning of its own and works only by
/// accumulating recognition, so a letter is camouflage on a home screen
/// already full of them. The owner's answer was to redraw the letter, and it
/// meets the objection on its own terms — the new `S` is a bold angled mark
/// built from two thick strokes, not the light monoline the argument was
/// about, and it holds at 60pt, which is the only test that matters.
///
/// `StrataMarkShape` above and `render_mark` in `tools/make_app_icon.py` both
/// stay. They are generated, they cost nothing, and the reasoning is on the
/// record if it is ever wanted again.
struct StrataMark: View {
    /// The block's side. The letter is sized off it.
    var side: CGFloat = 44

    /// How much of the block's side the letter takes.
    ///
    /// 0.52 rather than a tighter fit. The letter is 38 wide to 40 tall, so at
    /// 0.52 it sits well inside a block that still reads as a block. Past
    /// about 0.6 it starts to touch the rim and the two stop being separate
    /// objects.
    private static let capRatio: CGFloat = 0.52
    /// From the drawing's viewBox: 38 x 40.
    private static let aspect: CGFloat = 38.0 / 40.0

    var body: some View {
        BlockSurface(
            cornerRadius: GridConstants.blockCornerRadius(forCell: side),
            scale: side / GridConstants.blockReferenceCell
        ) {
            AppColors.warmBlack
        }
        .frame(width: side, height: side)
        .overlay {
            Image("StrataSMark")
                .renderingMode(.template)
                .resizable()
                .scaledToFit()
                .frame(width: side * Self.capRatio * Self.aspect,
                       height: side * Self.capRatio)
                .foregroundStyle(.white)
        }
        .accessibilityElement()
        .accessibilityLabel("Strata")
    }
}
